version: "3.8"

services:
        app:
                image: fairwrite-backend
                build: .
                ports:
                        - "8000:8000"
                volumes:
                        - .:/app
                command: uvicorn index:app --port 8000
